[target.x86_64-unknown-linux-musl]
rustflags = "-C target-feature=-crt-static"

[target.armv7-unknown-linux-musleabihf]
linker = "lld"
rustflags = "-C target-feature=-crt-static"

[target.armv-unknown-linux-musleabihf]
linker = "lld"
rustflags = "-C target-feature=-crt-static"

[target.aarch64-unknown-linux-musl]
linker = "lld"
rustflags = "-C target-feature=-crt-static"
