name: PowerView to MQTT Bridge
version: "latest"
slug: pv2mqtt
description: >
  Acts as a bridge between a Hunter Douglas PowerView Hub and Home Assistant, via the Home Assistant MQTT Integration.
url: https://github.com/wez/pview
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
services:
  - mqtt:need

apparmor: true

# Host network access is required for discovery of the bridge
host_network: true

schema:
  hub_ip: "str?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_bind_address: "str?"
  discovery_prefix: "str?"
  debug_level: "str?"
