name: PowerView to MQTT Bridge
image: ghcr.io/wez/pview-addon-{arch}
version: "latest"
slug: pv2mqtt
description: Control Hunter Douglas Shades via the PowerView Hub
url: https://github.com/wez/pview
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
services:
  - mqtt:need

apparmor: true

# Host network access is required for discovery of the bridge
host_network: true

schema:
  hub_ip: "str?"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_bind_address: "str?"
  discovery_prefix: "str?"
  debug_level: "str?"
